services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: workflow
      POSTGRES_PASSWORD: workflow
      POSTGRES_DB: workflow
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  maildev:
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'

volumes:
  postgres-data:
