services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: workflow
      POSTGRES_PASSWORD: workflow
      POSTGRES_DB: workflow
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  maildev:
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-data:/data

volumes:
  postgres-data:
  minio-data:
